boostcampwm-2022/iOS05-Segno

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Application/AppCoordinator.swift
Segno/Segno/Application/SceneDelegate.swift
Segno/Segno/Presentation/Coordinator/Coordinator.swift
Segno/Segno/Presentation/Coordinator/DiaryCoordinator.swift
Segno/Segno/Presentation/Coordinator/LoginCoordinator.swift
Segno/Segno/Presentation/Coordinator/MyPageCoordinator.swift
Segno/Segno/Presentation/Coordinator/TabBar/TabBarCoordinator.swift
Segno/Segno/Presentation/Coordinator/TabBar/TabBarPageCase.swift
Segno/Segno/Presentation/ViewController/DiaryViewController.swift
Segno/Segno/Presentation/ViewController/LoginViewController.swift
Segno/Segno/Presentation/ViewController/MyPageViewController.swift

11/10 #6
- 기본적인 Coordinator Protocol 생성
- protocol을 적용하여 Login / TabBar / Diary / MyPage에 해당하는 Coordinator 생성
- 각각의 Coordinator에서 직접적으로 띄워줄 임시 ViewController들 생성
- 추후에 Login 기능이 완성된다면, Login 여부에 따라 LoginCoordinator / TabBarCoordinator를 선택하여 화면에 표시하기

Coordinator 구현

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Application/AppCoordinator.swift
Segno/Segno/Application/SceneDelegate.swift
Segno/Segno/Entity/DiaryDetail.swift
Segno/Segno/Entity/DiaryListItem.swift
Segno/Segno/Entity/MusicInfo.swift
Segno/Segno/Extension/SHMediaItem+.swift
Segno/Segno/Presentation/Coordinator/Coordinator.swift
Segno/Segno/Presentation/Coordinator/DiaryCoordinator.swift
Segno/Segno/Presentation/Coordinator/LoginCoordinator.swift
Segno/Segno/Presentation/Coordinator/MyPageCoordinator.swift
Segno/Segno/Presentation/Coordinator/TabBar/TabBarCoordinator.swift
Segno/Segno/Presentation/Coordinator/TabBar/TabBarPageCase.swift
Segno/Segno/Presentation/ViewController/DiaryViewController.swift
Segno/Segno/Presentation/ViewController/LoginViewController.swift
Segno/Segno/Presentation/ViewController/MyPageViewController.swift

Develop -> Main 업데이트

---

Segno/Segno/Presentation/Coordinator/DiaryCoordinator.swift
Segno/Segno/Presentation/ViewController/DiaryViewController.swift

11/14 #18 
- SearchBar와 CollectionView 생성
- 나중에 ViewModel 등이 구현되면 이어줘야함
- 자세한 내용들은 TODO로 표시하였음

DiaryCollectionViewController 화면 구성

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Data/Network/Endpoint.swift
Segno/Segno/Data/Network/NetworkError.swift
Segno/Segno/Data/Network/NetworkManager.swift

11/14 #13 #17 
- Rx를 활용해 직접 요청을 보내는 private 함수와 외부에서 불러오는 함수로 나누어 작성
- 네트워킹 과정에서 발생할 수 있는 에러 케이스들에 대한 에러 작성
- 열거형으로 작성할 엔드포인트가 준수해야 할 몇 가지 기능에 대한 작성
- 논리적으로, 쿼리를 더해주고자 했던 해당 URL을 그대로 반환하는 것이 타당하다고 판단

네트워크 매니저 작성

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Data/Network/Endpoints/DiaryListItemEndpoint.swift
Segno/Segno/Data/Repository/DTO/DiaryListDTO.swift
Segno/Segno/Data/Repository/DTO/DiaryListItemDTO.swift
Segno/Segno/Data/Repository/DiaryRepository.swift

11/15 #28 #29 
- 일단은, 일기 목록을 받아오는 부분만 작성
- 일단 일기 엔티티와 동일하게 작성
- 목록을 나타내는 DTO 작성
- 예시 데이터 작성

일기 레포지토리 작성

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Domain/UseCase/DiaryListUseCase.swift

11/15 #30 #31
- getDiaryList() 메서드 작성하여 DTO를 DIaryListItem으로 매핑하여 반환

DiaryListUseCase 작성

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Data/Repository/DTO/DiaryListDTO.swift
Segno/Segno/Data/Repository/DiaryRepository.swift
Segno/Segno/Presentation/ViewController/DiaryCell.swift
Segno/Segno/Presentation/ViewController/DiaryCollectionViewController.swift

11/15 #34 #39 
- ViewModel과 바인딩을 구현
- DiaryCell 작성
- 위에서 바인딩한 데이터 출력
- 출력된 데이터 디자인 변경

DiaryCollectionViewController 작성

---

Segno/Segno/Application/AppCoordinator.swift
Segno/Segno/Presentation/Coordinator/TabBar/TabBarCoordinator.swift
Segno/Segno/Presentation/View/DiaryCell.swift
Segno/Segno/Presentation/ViewController/DiaryCollectionViewController.swift
Segno/Segno/Presentation/ViewController/LoginViewController.swift

11/22 #18 #22 
- 전체적인 디자인을 프로토타입에 맞춰 변경하였습니다
- 네비게이션 타이틀을 추가하였습니다.
- Diary 추가 버튼을 추가하였습니다.
- 전체적인 디자인을 수정하였습니다(TabBar Font 및 DiaryList Font)

전체적인 디자인 수정

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Data/Network/Endpoints/DiaryDetailEndpoint.swift
Segno/Segno/Data/Repository/DTO/DiaryDetailDTO.swift
Segno/Segno/Data/Repository/DiaryRepository.swift
Segno/Segno/Domain/UseCase/DiaryDetailUseCase.swift

11/23 #28 #81 #82 #83 
- DiaryRepository에 연결
- getDiary(id: String) 메소드를 작성하여 repository에 요청을 보내고, 받은 값을 DiaryDetail로 형변환
- DiaryDetailDTO 프로토타입을 작성
- 디버깅을 위한 더미데이터 작성
- 엔드포인트 프로토타입 작성
- item에 associated value String을 사용하여 queries로 전달
- Diary Detail 요청을 위한 getDiary 함수를 작성
- DiaryDetailEndpoint에 어떻게 id를 전달할지 고민하다가 enum에 String으로 전달하도록 하였습니다.

Diary detail logic 작성

---

Segno/Segno/Presentation/Coordinator/DiaryCoordinator.swift
Segno/Segno/Presentation/ViewController/DiaryCollectionViewController.swift

11/24 #94 
- DiaryCollectionViewController에서 + 버튼 선택시 Coordinator에게 알려서 DiaryEditViewController로 연결

일기 목록에서 + 버튼 누를 시 일기 추가 화면으로 연결

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Presentation/Coordinator/MyPageCoordinator.swift
Segno/Segno/Presentation/ViewController/MyPageViewController.swift
Segno/Segno/Presentation/ViewController/SettingsViewController.swift

11/24 #95 #96 #97 
- MyPageViewController에서 설정 버튼을 누르면 Coordinator에게 알려서 SettingsViewController로 연결

마이페이지 화면 세팅 및 설정 화면로 연결

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Entity/Location.swift
Segno/Segno/Extension/UIView+.swift
Segno/Segno/Presentation/Coordinator/DiaryCoordinator.swift
Segno/Segno/Presentation/View/LocationContentView.swift
Segno/Segno/Presentation/ViewController/MapKitViewController.swift

11/24 #98 
**_develop 브랜치가 아닌 feature/diary-detail-viewcontroller로 머지됩니다._**
- 기본적인 타이틀 라벨, close 버튼 및 MapView를 추가했습니다.
- MapView에는 전달받은 Location 정보를 바탕으로 해당 위치를 표시하며, 핀도 추가했습니다. 
- 추후 핀 클릭시 구체적인 장소(식당 이름, 카페 이름 등)를 표시하는 기능을 추가할 수 있다면,, 좋겠습니다! 
- MapView에서 사용하려면 기본적으로 Double타입이어야 했기 때문에 이같이 변경했습니다.

MapKitViewController 작업

---

Segno/Segno/Presentation/ViewController/MapKitViewController.swift

11/28 #98
- 추후 `private func bindLocationItem(location: Location)` 에 Location을 string으로 변경하는 메서드 작성이 필요합니다.

MapKitViewController에 주소 라벨 추가

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Presentation/View/NicknameCell.swift
Segno/Segno/Presentation/View/SettingsActionSheetCell.swift
Segno/Segno/Presentation/View/SettingsSwitchCell.swift
Segno/Segno/Presentation/ViewController/DiaryCollectionViewController.swift
Segno/Segno/Presentation/ViewController/MyPageViewController.swift
Segno/Segno/Presentation/ViewController/SettingsViewController.swift
Segno/Segno/Presentation/ViewModel/MyPageViewModel.swift

11/29 #95 #96 
- 기존 버튼 방식 대신 윤종님(#108 )의 코드를 참고하여 TableView를 사용함으로 전체적인 디자인 통일성을 맞췄습니다.

MyPageViewController 디자인 조정

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Data/Network/Endpoints/UserDetailEndpoint.swift
Segno/Segno/Data/Repository/DTO/UserDetailDTO.swift
Segno/Segno/Data/Repository/MyPageRepository.swift
Segno/Segno/Domain/UseCase/UserDetailUseCase.swift
Segno/Segno/Entity/UserDetailItem.swift
Segno/Segno/Presentation/ViewController/MyPageViewController.swift
Segno/Segno/Presentation/ViewModel/MyPageViewModel.swift

11/30 #130 #131 #132 #133 #134 #136 #137 #138 #139
- ViewController <-> ViewModel <-> UseCase <-> Repository <-> Server 에 이르는 플로우들 전체적으로 구현하였습니다.
- 하지만 아직 코드들을 깔끔하게 정리하진 못하였습니다. 일단 구현에만 우선적으로 집중했다는 점 말씀드립니다.
- 기존에 윤종님이 작성하셨던 것을 참고하였기에
```
Observable<[MyPageCellModel]>.just([
.writtenDiary(title: "작성한 일기 수", subtitle: "123,456,789개"),
.settings(title: "설정"),
.logout(title: "logout", color: .red)
])
```
코드에서 subtitle에만 값을 변경해서 주면 되는데, 해당 내용을 어떻게 해야할지 생각이 안떠올라서 우선 무작정 viewModel.writtenDiaryObservable.subscribe 내에 때려박았습니다...
- 내일 다시 코드 들여다보고 수정해보겠습니다.
- 실행은 잘 되는데, 프리뷰만 안되서 혹시 다른 분들도 문제가 생길지 우려가 됩니다.

MyPage와 관련된 플로우 작성

---

Segno/Segno/Presentation/ViewController/LoginViewController.swift

12/05
- https://github.com/SnapKit/Masonry/issues/160 를 참고하여 holder를 만들어서 수정하였습니다.
- iPhone 8
- iPhone 14

Login View 수정

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Segno/Segno/Application/AppDelegate.swift
Segno/Segno/Data/Network/Endpoints/LoginEndpoint.swift
Segno/Segno/Data/Repository/LoginRepository.swift
Segno/Segno/Data/Session/LoginSession.swift
Segno/Segno/Domain/UseCase/LoginUseCase.swift
Segno/Segno/Presentation/View/NicknameCell.swift
Segno/Segno/Presentation/View/SettingsActionSheetCell.swift
Segno/Segno/Presentation/ViewController/LoginViewController.swift
Segno/Segno/Presentation/ViewController/MyPageViewController.swift
Segno/Segno/Presentation/ViewController/SettingsViewController.swift
Segno/Segno/Presentation/ViewModel/LoginViewModel.swift
Segno/Segno/Resource/Info.plist

12/7 #22 #95 #96 
- UI 출력과 관련하여 나오는 여러 Error / Warning들 처리
- separator line이 왼쪽으로는 일부 떨어져있으나, 오른쪽은 끝까지 연결되어 있는 현상 수정
- GoogleLogin과 관련된 모든 로직들 삭제
- 애플 로그인 디자인 변경
- MyPage와 Settings 내에서는 여러 셀들(NicknameCell, SettingsSwitchCell, SettingsActionSheetCell)을 register하여 reuse 합니다.
- 해당 셀 class 내에서 직접적으로 contentView의 크기를 건드리면 바로 해결되지만, contentView를 건들면 Warning이 뜨게 됩니다.
- 결국 이를 해결하기 위하여 UITableViewDelegate를 상속받아 heightForRowAt로 높이 값을 직접 줌으로 임시해결하였습니다.
- 더 좋은 방법을 아신다면 알려주세요!

전체적인 UI 수정

---

Segno/Segno/Presentation/View/DiaryCell.swift
Segno/Segno/Presentation/ViewController/DiaryCollectionViewController.swift

12/8 #95 #118 
- UITapGesture를 이용하여 탭이 되도록 하였습니다.
- 불필요한 외곽선들 삭제와 색상을 이쁘게 수정했습니다.

DiaryCollectionViewController 검색 기능 및 UI 수정

---

Segno/Segno/Data/Repository/DTO/NewDiaryDetailDTO.swift
Segno/Segno/Domain/UseCase/DiaryEditUseCase.swift
Segno/Segno/Presentation/ViewController/DiaryEditViewController.swift
Segno/Segno/Presentation/ViewModel/DiaryEditViewModel.swift

12/9
- 서버 명세에 반영되지 않은 DTO 수정했습니다.
- 작성 뷰를 dismiss(popViewController) 했습니다.
- 응답 로직을 전체적으로 수정했습니다.

DiaryEditViewcontroller - DTO 수정에 따른 서버로부터의 응답 로직 수정

---

Segno/Segno/Application/AppCoordinator.swift
Segno/Segno/Data/Repository/DiaryRepository.swift
Segno/Segno/Data/Repository/LocalUtilityRepository.swift
Segno/Segno/Data/Repository/MyPageRepository.swift
Segno/Segno/Data/Repository/SettingsRepository.swift
Segno/Segno/Domain/UseCase/DiaryEditUseCase.swift
Segno/Segno/Domain/UseCase/LoginUseCase.swift
Segno/Segno/Presentation/Coordinator/MyPageCoordinator.swift
Segno/Segno/Presentation/ViewController/MyPageViewController.swift
Segno/Segno/Presentation/ViewModel/DiaryEditViewModel.swift

12/8 #16  #191 
- 서버와 통신할 때 사용하는 Token을 keyChain에 저장하도록 리팩토링 진행하였습니다.
- 드디어 AppCoordinator에서 일일이 수정할 필요 없이 keyChain에 값이 있는지 여부에 따라서 LoginView 혹은 DiaryCollectionView로 넘어가도록 하였습니다.
- KeyChain과 관련하여 MyPage에서 logout 버튼을 누르면 AppCoordinator까지 올라가서 로그아웃을 해야하는데, delegate를 두 번 사용하여 거슬러 올라가는게 최선인지 고민중에 있습니다.
- Repository가 다른 Repository나, Coordinator, ViewModel을 넘나드는 모습에서 괴리감을 느꼈습니다.
- 아무래도 Repository보다는 Manager 등이 되는게 낫지 않을까 생각됩니다.
- 다른 의견 환영합니다 :)

KeyChain 작업

---

Segno/Segno/Presentation/ViewController/DiaryCollectionViewController.swift
Segno/Segno/Presentation/ViewController/MyPageViewController.swift

12/10
- 일기 목록 화면에서 컬렉션 뷰를 위로 드래그하면 새로고침 하도록 기능 추가하였습니다.
- 일기 목록 화면이 다시 보일 때(viewWillAppear) 컬렉션 뷰를 새로고침 하였습니다.
- 마이페이지 화면 역시 다시 보일 때 닉네임과 작성한 일기 개수를 새로고침 하였습니다.

일기 목록과 마이페이지 새로고침

---

Segno/Segno/Presentation/ViewController/DiaryDetailViewController.swift
Segno/Segno/Presentation/ViewController/DiaryEditViewController.swift

12/11
- 바디에 내용을 전달하지 않았던 어처구니 없던 오류였습니다...
- 대가리 일단 박습니다..

fix: bodyTextView의 내용을 불러올 수 없던 오류 수정
