boostcampwm-2022/iOS05-Segno

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Presentation/Coordinator/DiaryCoordinator.swift
Segno/Segno/Presentation/ViewController/DiaryCollectionViewController.swift

11/15 #18 #34
- 파일명 및 클래스 명 수정(DiaryViewController -> DiaryCollectionViewController)
- 색상과 관련된 magic number 제거 및 appColor 적용
- AutoLayout 대신 SnapKit으로 적용
- CollectionViewFlowLayout을 Coordinator가 아닌 ViewController에서 만들도록 수정
- CollectionViewFlowLayout을 Coordinator가 아니라 ViewController에서 만드는게 옳다고 생각하였습니다.
- Coordinator의 경우 단순히 ViewController를 띄워줄 뿐, 해당 뷰 컨트롤러의 속성인 Layout을 만드는 역할을 하는 것은 바람직하지 않다고 생각했습니다.

DiaryCollectionViewController 화면 구성-2

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Data/Network/Endpoints/DiaryListItemEndpoint.swift
Segno/Segno/Data/Network/Endpoints/LoginEndpoint.swift
Segno/Segno/Data/Network/Namespaces/BaseURL.swift
Segno/Segno/Data/Repository/DTO/TokenDTO.swift
Segno/Segno/Data/Repository/DTO/UserInfoDTO.swift
Segno/Segno/Data/Repository/LoginRepository.swift

11/16 #46 #47 #48 
- OAuth 인증 후 이메일과 회사 정보를 서버에 전송해 자체 서버 로그인을 요청합니다.
- 서버에서 온 응답을 토큰(이후 이름을 포함한 유저 정보로 수정될 가능성이 높음) DTO로 디코딩한 후 발신합니다.
- 회사 정보와 사용한 이메일을 사용하게끔 작성했습니다.
- 추후 다른 방식으로 변경되면, 변경의 소지가 있습니다.
- 각고의 고민 끝에, View Controller에서 다루는 것이 적합하다고 생각해 레포지토리에서는 다루지 않았습니다.
- Wiki의 "주간 Dal Segno"에 상세히 기술할 예정입니다.
- 로그인했을 때 사용자가 자신의 닉네임을 볼 수 있어야 한다고 판단했습니다. 그래서 로그인했을 때 서버로부터 이름을 받아올 수 있으면 좋겠다고 생각했습니다. 향후 닉네임 변경 기능이 추가될 것을 감안했습니다.
- 일단 현재의 작동을 위해 토큰만을 가져오는 DTO를 만들었고, 명세가 바뀌면 유연하게 대응할 수 있는 유저 정보 DTO도 구현해 두었습니다. 향후 서버 명세의 확정에 따라 한 가지를 삭제할 예정입니다.

로그인 레포지토리 작성

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Domain/UseCase/LoginUseCase.swift

11/17 #51 #53 
- sendLoginRequest(email: ) 메서드를 통해 TokenDTO를 정상적으로 받으면 .success(true)를, 실패한 경우 .failure(error)를 ViewModel로 리턴합니다.
- 두 가지 이슈를 한 번에 처리하여 고민된 사항이나, 두 이슈를 분리하기가 사실상 어렵다고 생각되어 한 번에 커밋하였습니다.

LoginUseCase 작성

---

Segno/Segno/Application/AppCoordinator.swift
Segno/Segno/Application/AppDelegate.swift
Segno/Segno/Data/Network/Endpoints/LoginEndpoint.swift
Segno/Segno/Data/Network/NetworkManager.swift
Segno/Segno/Data/Repository/DTO/TokenDTO.swift
Segno/Segno/Data/Repository/DiaryRepository.swift
Segno/Segno/Data/Repository/LocalUtilityRepository.swift
Segno/Segno/Data/Repository/LoginRepository.swift
Segno/Segno/Domain/UseCase/LoginUseCase.swift
Segno/Segno/Entity/DiaryDetail.swift
Segno/Segno/Presentation/Coordinator/LoginCoordinator.swift
Segno/Segno/Presentation/ViewController/DiaryCollectionViewController.swift
Segno/Segno/Presentation/ViewController/LoginViewController.swift
Segno/Segno/Presentation/ViewModel/LoginViewModel.swift

11/17
- 이제 뷰 컨트롤러에서 뷰모델 유즈케이스 ... 다시 뷰모델까지 돌아옵니다.
- 명세대로 파라미터에 태워서 보냈는데, 응답이 수상쩍습니다. 404 not found가 뜹니다.
- 혹시 서버가 내려가 있나요?

로그인 플로우 확립

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Data/Session/LoginSession.swift
Segno/Segno/Domain/UseCase/LoginUseCase.swift
Segno/Segno/Entity/UserInfo.swift
Segno/Segno/Presentation/ViewController/LoginViewController.swift
Segno/Segno/Presentation/ViewModel/LoginViewModel.swift
Segno/Segno/Resource/Info.plist

11/22 #43 #45 #46 #60 #61 #64 #66 
- 뷰 컨트롤러와 뷰 모델에 붙어 있던, 구글 로그인 서버에 요청하는 과정을 이관했습니다.
- 토큰 자체는 키체인에 저장하도록 했습니다.
- 향후 로컬 유틸리티 레포지토리에 적절한 처리를 할 계획입니다.
- 반응형 프로그래밍이란, 시간에 따른 이벤트의 흐름이 변화하는 것을 감지해 작동하는 것입니다. 따라서, 응답을 받아오는 데 "시간"이 걸리는 작업, 대표적으로 비동기 작업에 활용합니다.
- 하지만 키체인에서 유저 데이터를 받아오는 작업의 경우 비동기 작업이 아닙니다. 따라서 반응형 프레임워크 Rx를 사용하는 것은 과도하다고 판단했습니다.
- 이에 따라 리팩토링한 후 연동할 계획입니다.
- 키체인에 토큰을 저장하는 이유는, 보안을 유지하기 위함입니다.
- 전통적인 키체인의 사용법에 의하면, id와 패스워드를 저장한다고 할 때, id를 키로써 사용해 패스워드에 해당하는 토큰을 가져와야 합니다.
- 하지만 만약 그렇다면, id에 해당하는 이메일에 대한 정보를 일기 목록 뷰 컨트롤러와 마이페이지 뷰 컨트롤러가 알고 있어야 합니다. 이를 위해서는 로그인 코디네이터 - 앱 코디네이터 - 탭 바 코디네이터 - 목표 코디네이터에 이르는 데이터 전달 과정이 필요합니다.
- 일단 이에 대해서는 유보 상태입니다.

로그인 프로세스 분리

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Presentation/View/LocationContentView.swift
Segno/Segno/Presentation/View/MusicContentView.swift
Segno/Segno/Presentation/View/TagView.swift
Segno/Segno/Presentation/ViewController/DiaryDetailViewController.swift

11/22 #71 
- TagView는 스크롤뷰와 horizontal 방향의 스택뷰를 이용하여 구현하였습니다.
- 음악 컨텐츠를 표시하기 위한 MusicContentView를 생성했습니다. 네이밍의 변화가 필요한 경우 자유롭게 이야기 해주셔도 됩니다.
- 커밋 내역 중 옥의 티가 존재하는 점 사과드립니다. 🙇🏻‍♂️
- preview 확인을 위해 SwiftUI를 활용하였습니다. 추후 제거 예정입니다.
- 킹받는 색상으로 제작하였습니다.
- 오류가 뜨는 문제는 런타임에서 레이아웃 관련 문제로 인한 것이었습니다. 
- 아예 뜨지 않는 문제는 `Option + Command + Enter` 입력하니 해결되었습니다.

DiaryDetailViewController 화면 구성

---

Segno/Segno/Presentation/Coordinator/DiaryCoordinator.swift
Segno/Segno/Presentation/ViewController/DiaryCollectionViewController.swift

11/23 #80 
- DiaryCollectionViewController에서 셀 선택시 Coordinator에게 알려서 DiaryDetailViewController로 연결
- TODO로 두었듯이, 아직 DiaryDetailViewController에서 ViewModel 등이 구현되지 않아 우선 ViewContoller를 띄워주기만 함

일기 목록에서 셀 선택시 일기 상세 화면으로 연결

---

Segno/Segno/Presentation/View/LocationContentView.swift
Segno/Segno/Presentation/View/MusicContentView.swift
Segno/Segno/Presentation/View/TagView.swift
Segno/Segno/Presentation/ViewController/DiaryDetailViewController.swift

- 11/23 #71 #75 
- 앱 내 지정된 색상과 폰트를 활용하였습니다.
- tagLabel에 inset을 부여하여 여백을 설정하고,
- cornerRadius를 깎았습니다.
- 최상위 스크롤뷰 하위에 있는 스택뷰에 Inset을 부여했습니다.
위 이미지는 stackView의 Inset을 16, width의 Inset도 32로 부여한 경우입니다.
```swift
stackView.snp.makeConstraints {
$0.edges.equalTo(scrollView).inset(16)
$0.width.equalTo(scrollView.snp.width).inset(32)
}
```
제 판단으로는 stackView의 inset을 좌우 각각 16씩 뺐기 때문에, 정상적으로 width를 설정하려면 scrollView의 width에서 16*2 = 32를 빼야 할 것 같았습니다.
하지만
```swift
stackView.snp.makeConstraints {
$0.edges.equalTo(scrollView).inset(16)
$0.width.equalTo(scrollView.snp.width).inset(16)
}
```
위 이미지는 stackView의 Inset을 16, width에도 16을 부여해야지 원하는 레이아웃이 나왔습니다.
일단 원하는 바는 이뤘지만, 머릿속으로 정리되지 않은 부분이라 일단 공유드려봅니다. 더 알아보겠습니다.
- 일단 뷰컨트롤러에 노래 제목, 아티스트, 앨범 아트 이외의 다른 것까지 띄우기는 공간적인 제약이 있어 album을 활용하지 못할 것 같습니다. 추후 album 프로퍼티가 …

DiaryDetailViewController  레이아웃 수정

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Data/Repository/DTO/DiaryListDTO.swift
Segno/Segno/Domain/UseCase/DiaryListUseCase.swift
Segno/Segno/Entity/DiaryDetail.swift
Segno/Segno/Entity/DiaryListItem.swift
Segno/Segno/Presentation/ViewController/DiaryEditViewController.swift

11/25 #85
- 구성 요소로는 제목 텍스트 필드, 이미지 뷰, 내용 텍스트 뷰, 태그 스크롤 뷰, 음악 버튼과 레이블, 위치 버튼과 레이블이 있습니다.
- 특히 버튼을 만들 때 높이와 너비를 같게 만드는 것부터가 어려웠습니다.
- 아직 SnapKit에 익숙하지 않아 벌어진 일이라, 더 공부하면 될 것 같습니다.
- 내비게이션 아이템을 세팅해주려면 내비게이션 바가 있어야 하는데, 그러려면 내비게이션 컨트롤러가 있어야 합니다.
- 일단은 코디네이터를 거쳐 모달하게 띄워 준다면 내비게이션 바는 생길 것이므로 괜찮습니다.
- 하지만 모달하게 띄울 화면인데 굳이 내비게이션 컨트롤러를 새로 만들어 사용해야 할까? 는 생각해 볼 문제인 것 같습니다.
- 일기 상세 뷰 컨트롤러에 이미 작성되어 있는 뷰 컨트롤러의 익스텐션 덕에, 작성 뷰에 대한 프리뷰 코드만 넣어 주고 바로 프리뷰를 볼 수 있었습니다.
- 이렇듯 다른 뷰 컨트롤러, 나아가 다른 여러 뷰에서도 사용할 가능성이 있는 코드라면 베이스 뷰 컨트롤러에 모아서 구현하는 것도 좋다고 생각했습니다.
- 나아가 프리뷰를 반환하는 static var도 범용성있게 만들 수는 없을까? 생각했습니다.

일기 작성 뷰 컨트롤러 레이아웃 작성

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Presentation/ViewModel/DiaryDetailViewModel.swift

11/23 #89 
- 유즈케이스의 getDiary(id:) 메서드를 호출하여 DiaryDetail을 받아 이를 PublishSubject 타입의 diaryItem에 넣어줍니다.
- diaryItem를 매핑하여 생성하였습니다.
- 후자의 경우, viewModel.diaryItem을 처리하는 로직이 매우 길어질 것이라 예상되어 전자의 방법으로 작성했습니다.

DiaryDetailViewModel 작성

---

Segno/Segno/Presentation/ViewController/DiaryEditViewController.swift

11/24 #85 
- 각 컴포넌트의 색상을 조절했습니다.
- 하드 코딩되어 있는 값들은 전부 Metric 네임스페이스로 분리했습니다.
- 전체 뷰로부터 약간의 패딩을 주었습니다.
- 주로 스택 뷰에 addArrangedSubview를 하는 과정에서 발생한 문제입니다. 화면이 스택 뷰 + 스크롤 뷰의 형식이다 보니, 자연스럽게 발생하는 문제입니다.
- 이를 위해 UIStackView Extension으로 addArrangedSubviews 메서드를 따로 작성하려고 생각하고 있습니다.
- 하지만 지금의 형식 또한 코드가 위 아래로 길기는 하지만, 무엇을 언제 세팅하는지 보기 좋다는 장점은 있습니다. 그래서 고민 중입니다.
- 당장은 컴포넌트를 세팅했지만, 유저 경험이 불편할 만 한 요소가 있습니다. 음악 버튼이나 위치 버튼의 크기, 너무 가까이 붙어 있는 저장 버튼 등의 요소가 있습니다.

일기 작성 뷰 컨트롤러 디자인 조정

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Entity/Location.swift
Segno/Segno/Presentation/Coordinator/DiaryCoordinator.swift
Segno/Segno/Presentation/View/LocationContentView.swift
Segno/Segno/Presentation/View/MusicContentView.swift
Segno/Segno/Presentation/ViewController/DiaryCollectionViewController.swift
Segno/Segno/Presentation/ViewController/DiaryDetailViewController.swift
Segno/Segno/Presentation/ViewController/MapKitViewController.swift
Segno/Segno/Presentation/ViewModel/DiaryDetailViewModel.swift

11/24 #71 #74 #89 
- DetailCollectionViewController를 건드려야 하는 부분이라 DetailCollectionViewController에서 작업했습니다.
- CLLocation이 존재함에도 이를 생성한 이유는 Location을 작성한 이유는 고민한 점에 작성했습니다.
- 편집을 위해 도입했던 delegate 함수도 제거했습니다.
- DetailViewController에서 지도 버튼을 누르면 델리게이트 함수 및 코디네이터를 경유하여 위치 데이터를 전달해야 합니다.
- 근데 CLLocation을 직접 전달할 경우, ViewController 및 Coordinator에 까지 `CoreLocation` 을 임포트 해야 하는 문제가 있었습니다. ViewController는 그렇다손 치더라도 Coordinator에 CoreLocation을 임포트하는 것은 선을 넘었죠.
- 따라서 LocationContentView에서 버튼을 tap 할 경우 CLLocation에서 위도 및 경도 정보만 담을 수 있는 Location으로 변환되어 이 정보를 전달하도록 했습니다. 위도와 경도 정보는 String으로 저장되어 Location을 사용하는 곳에서 `CoreLocation`을 임포트 할 필요가 없습니다.

DiaryDetailViewController 작업

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Application/AppCoordinator.swift
Segno/Segno/Data/LoginError.swift
Segno/Segno/Data/Session/LoginSession.swift
Segno/Segno/Presentation/ViewModel/LoginViewModel.swift

11/28
- 구글 로그인 결과를 PublishSubject<Result> 타입이 아닌 Observable<String>으로 변경
- 애플 로그인 특성 상 델리게이트 함수를 이용해야 했습니다. 이로 인해 Observable을 리턴하는 방식으로 리팩토링 하는 것은 불가능했습니다. 그래서 우선 그대로 놔뒀습니다. 애플 로그인과 구글 로그인이 동일한 방식이 아니라 다소 아쉬웠습니다.

refactor: 구글 로그인 결과를 String 타입의 Observable로 넘기도록 변경

---

Segno/Segno/Data/Repository/LocalUtilityRepository.swift

11/28
- RxSwift와 관련된 모든 부분을 제거(Single 등)
- KeyChain을 사용하는 전체적인 메소드들에서 key를 parameter로 가져올 필요가 없어짐.

LocalUtilityReposity 리팩토링

---

Segno/Segno/Data/Session/LoginSession.swift
Segno/Segno/Presentation/ViewController/LoginViewController.swift
Segno/Segno/Presentation/ViewModel/LoginViewModel.swift

11/29
- 애플 로그인을 위해 import하는 AuthorizationServices에 UI 관련 요소가 들어 있기 때문입니다.
- 되게 많은데, 대표적으로는 AuthenticationServices.ASAccountAuthenticationModificationViewController 가 있겠습니다.
- 이제 뷰 컨트롤러가 로그인 세션 객체를 들고 있고, 세션에서 인증 과정을 거친 다음 해당 정보를 토대로 자체 서버에 로그인 요청을 보내게 됩니다.

애플 인증 관련 요소를 뷰 모델에서 제거

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Data/Repository/UserDefaultsKey.swift
Segno/Segno/Presentation/View/NicknameCell.swift
Segno/Segno/Presentation/View/SettingsActionSheetCell.swift
Segno/Segno/Presentation/View/SettingsSwitchCell.swift
Segno/Segno/Presentation/ViewController/SettingsViewController.swift
Segno/Segno/Presentation/ViewModel/SettingsViewModel.swift

11/29 #96 #112 
- 기존에 tableView의 row 값이라는 하드 코딩 데이터를 이용하여 액션을 식별하는 것이 바람직하지 않다고 생각하여 위 방식으로 변경하였습니다.
- 유즈케이스 작성 및 연결은 내일 진행하도록 하겠습니다.
- 금일 피드백을 반영하여, 위 방향으로 변경했습니다. 자세한 사항은 밑에 기술했습니다.
- 셀도 View이니 ViewModel을 주입받아도 되지 않을까 싶었는데, 셀에 뷰모델을 주입하는 건 과하다는 피드백을 반영하여 셀에 뷰모델을 직접 주입하지 않고, PublishSubject를 통해 ViewController에서 이벤트를 관찰하도록 하고, 필요에 따라 completionHandler도 이용하는 방식으로 변경했습니다.
- 액션 시트, Alert도 코디네이터를 이용해야 하는지 저희가 이야기 한 적 있었는지 제가 잘 기억이 나지 않아서,,, 코멘트 달아주시면 감사하겠습니다. 일단 코디네이터를 이용하지 않는 방향으로 작성해봤습니다. 어느 방향이든 추후 extension으로 분리하긴 해야합니다.

SettingsViewController에서 Cell 내부 액션을 이용하는 방법 변경

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Data/Repository/SettingsRepository.swift
Segno/Segno/Domain/UseCase/ChangeUserNameUseCase.swift
Segno/Segno/Domain/UseCase/SettingsUseCase.swift
Segno/Segno/Presentation/Utility/DarkMode.swift
Segno/Segno/Presentation/View/SettingsCellModel.swift
Segno/Segno/Presentation/ViewController/SettingsViewController.swift
Segno/Segno/Presentation/ViewModel/SettingsViewModel.swift

11/30 #125 #126 #127 #128 
- 긴급회의에서 논의된 내용에 따라 닉네임 변경하는 메서드는 ChangeUserNameUseCase에 작성했습니다.
- SettingsUseCase에선 LocalUtilityRepository의 UserDefaults 관련 함수를 활용하여 UISwitch 버튼 전환, 액션 시트 클릭에 따른 value를 저장합니다.
- dataSource의 초기값을 `getAutoPlayMode()`, `getDarkMode()` 메서드를 이용해 지정하여 뷰에 처음 진입했을 때 저장되어 있는 값이 불러와지도록 합니다.

SettingsUseCase 및 ChangeUserNameUseCase 작성

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Data/Network/Endpoint.swift
Segno/Segno/Data/Network/Endpoints/ChangeNicknameEndpoint.swift
Segno/Segno/Data/Repository/SettingsRepository.swift
Segno/Segno/Domain/UseCase/ChangeNicknameUseCase.swift
Segno/Segno/Domain/UseCase/ChangeUserNameUseCase.swift
Segno/Segno/Presentation/ViewController/SettingsViewController.swift
Segno/Segno/Presentation/ViewModel/SettingsViewModel.swift

12/1 #127 #128 #145 #146 
- SettingsVC, SettingsViewModel, ChangeNicknameUseCase, SettingsRepository에 이르는 전체적인 흐름을 구축했습니다.
-  서버 명세에 따라 ChangeNickNameEndpoint를 생성했습니다.
- HTTPMethod 열거형에 PATCH를 추가했습니다.

SettingsRepository 및 닉네임 변경 구현

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Data/Network/Endpoints/DiaryDeleteEndpoint.swift
Segno/Segno/Data/Network/Endpoints/DiaryPostEndpoint.swift
Segno/Segno/Data/Repository/DiaryRepository.swift

12/05
- id, token만 보내면 되기에 추가적인 entity는 작성하지 않았습니다.
- 삭제를 할 경우 추가적인 팝업이 나오지 않고, 추가적인 작업이 필요하지 않으므로 항상 true를 반환하도록 하였습니다.
로직상으로는 문제가 없다고 생각됩니다. 서버 작성 완료 후 테스트하고 문제가 있을 경우 수정하겠습니다.
- Void를 하는게 맞나 싶습니다.

Diary Delete Logic 추가

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Application/SceneDelegate.swift
Segno/Segno/Data/Manager/DarkModeManager.swift
Segno/Segno/Data/Repository/LocalUtilityRepository.swift
Segno/Segno/Domain/UseCase/SettingsUseCase.swift
Segno/Segno/Presentation/View/NicknameCell.swift
Segno/Segno/Presentation/ViewController/SettingsViewController.swift
Segno/Segno/Presentation/ViewModel/SettingsViewModel.swift
Segno/Segno/Resource/Assets.xcassets/background.colorset/Contents.json
Segno/Segno/Resource/Assets.xcassets/grey1.colorset/Contents.json
Segno/Segno/Resource/Assets.xcassets/grey2.colorset/Contents.json
Segno/Segno/Resource/Assets.xcassets/grey3.colorset/Contents.json

12/6 #157 #159 #160 
- 다크모드 설정시 보여줄 색상이 지정되어 있지 않아 추가했습니다.
- 앱이 처음 실행될 때 SceneDelegate에서도 저장된 값에 따라 다크모드가 바로 설정될 수 있도록 DarkModeManager를 싱글톤으로 별도로 생성하였습니다.
- DarkModeManager는 LocalUtilityRepository로부터 UserDefaults값을 가져와 뷰를 직접적으로 업데이트해주는 역할을 수행합니다.
- SceneDelegate에서 다크모드 설정을 해주기 위한 고육책이었지만, DarkModeManager를 SettingUseCase에서 이용하는게 맞나 하는 고민을 했습니다. 유즈케이스가 유즈케이스를 이용하는 격이기 때문입니다. 
- 다만 이렇게 하지 않을 경우 코드의 일관성이 저하됩니다. 이로 인해 일단 유즈케이스에서 DarkModeManager을 이용하도록 작성해놓았습니다. 이부분에 대한 의견 부탁드립니다!

다크모드 기능 구현

---

Segno/Segno/Data/Repository/DTO/DiaryListDTO.swift
Segno/Segno/Presentation/ViewController/DiaryCollectionViewController.swift

12/6 #118 
- 제목에 한하여서 검색 기능 구현
- 아래 gif를 첨부하였는데, 마지막에 보면 검색을 하고 모두 지운 상태에서는 검색 완료도 취소도 되지 않습니다
- 그래서 심지어 DiaryDetail로 넘어갔다 왔음에도 불구하고 여전히 검색창이 켜져있는 것(커서가 깜빡임)을 볼 수 있습니다
- tapGesture 등으로 다른 곳(collectionView?)이 선택되면 ```searchBar.endEditing(true)```로 강제종료를 하는게 최선인지 고민중입니다.

DiaryCollectionViewController 검색 기능 구현

---

Segno/Segno/Presentation/ViewController/DiaryEditViewController.swift

12/6 #85 
- ScrollView가 한 번의 터치는 먹어버리는 문제가 있었습니다.
- 이에 ScrollView에 UITapGestureRecognizer를 등록하고, 액션 함수 내부에 `self.view.endEditing(true)`를 작성하여 화면 터치 시 키보드가 내려가도록 했습니다.
- 
- photoImageView.isUserInteractionEnabled = true로 해결했습니다.
- 다양한 경우의 수가 있어 애로가 많았습니다.
- textView가 시중의 예제와는 달리 화면의 맨 밑에 있는 것이 아니라 중간에 위치합니다.
- 별다른 처리를 안해주면 스크롤의 위치가 맨 위일때는 키보드로 인해 텍스트뷰가 가려지지만,
- 이를 위해 뷰의 위치를 키보드 높이만큼 올려주는 식으로만 처리해버리면, 텍스트뷰가 화면 상의 상단에 위치할 때 터치 시 텍스트뷰가 화면을 벗어나게 됩니다.
- 이를 해결하려면 텍스트뷰의 슈퍼뷰상 위치(textView.frame.minY) , 스크롤뷰의 현재 화면 위치(mainScrollView.contentOffset.y), 키보드의 높이를 모두 고려해야 했습니다.
- 여러 번의 테스트 끝에 적절한 공식을 찾아내어 처리했습니다.

DiaryEditViewController 터치, 키보드 관련 이슈 처리

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Data/Network/Endpoints/DiaryDetailEndpoint.swift
Segno/Segno/Data/Network/Endpoints/DiaryListItemEndpoint.swift
Segno/Segno/Data/Repository/DTO/DiaryDetailDTO.swift
Segno/Segno/Data/Repository/DTO/DiaryListDTO.swift
Segno/Segno/Data/Repository/DiaryRepository.swift
Segno/Segno/Data/Repository/MusicRepository.swift
Segno/Segno/Data/Session/MusicSession.swift
Segno/Segno/Domain/UseCase/DiaryDetailUseCase.swift
Segno/Segno/Domain/UseCase/DiaryListUseCase.swift
Segno/Segno/Domain/UseCase/PlayMusicUseCase.swift
Segno/Segno/Presentation/View/MusicContentView.swift
Segno/Segno/Presentation/ViewController/DiaryDetailViewController.swift
Segno/Segno/Presentation/ViewModel/DiaryDetailViewModel.swift

12/7 #90 #142 #156 
- Repository에서 재생 요청을 보내게 됩니다.
- 음악 플레이어는 뷰와 무관한 객체고, 직접 기기의 미디어 재생 수단과 연결되기 때문에 이렇게 하는 것이 가능합니다.
- 음악 재생을 테스트하기 위해 구조를 뜯다가 수행했습니다.
- 일기 목록 URL에 쿼리만 붙여주면 되더군요..?
- 이를 위해 뷰 모델에 재생중이냐 아니냐를 나타내는 프로퍼티는 있어야 할 것 같습니다.
- 일기를 보는 동안은 무한 반복이 돼야 하는데, 그것은 아직 구현하지 못했습니다.

뮤직 세션 레이어 분리

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Extension/UIViewController+.swift

12/8
- 기본적으로 제목과 메시지를 입력합니다.
- OK만 있는 팝업, Cancel과 OK가 있는 팝업을 구현했습니다.
- 후자의 경우, action 파라미터가 있고, OK를 눌렀을 때의 동작을 클로저 안에 넣어 주면 됩니다.
---
사용 예시
``` swift
class ViewController {
private func searchTapped() {
//        shazamSession.toggleSearch()
makeCancelOKAlert(title: "검색한다", message: "진짜 한다") { _ in
self.shazamSession.toggleSearch()
}
}
}
```

Alert 팝업을 위한 extension 작성

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Application/AppCoordinator.swift
Segno/Segno/Data/Session/LocationRepository.swift
Segno/Segno/Domain/UseCase/LocationUseCase.swift
Segno/Segno/Presentation/Utility/DeleteTapGestureRecognizer.swift
Segno/Segno/Presentation/View/TagView.swift
Segno/Segno/Presentation/ViewController/DiaryEditViewController.swift
Segno/Segno/Presentation/ViewModel/DiaryEditViewModel.swift

12/7 #166 #168 #171
- 이 과정에서 텍스트필드를 새롭게  작성했으며, 관련하여 키보드 가림 이슈를 다시 수정했습니다.
- 뷰컨트롤러를 제공할 필요가 없어, session이 아닌 일반적인 클린 아키텍처 흐름으로 구성했습니다.

DiaryEditViewController 구성 / Location 흐름 구축

---

Segno/Segno/Data/Network/Endpoints/UserDetailEndpoint.swift
Segno/Segno/Data/Repository/DTO/UserDetailDTO.swift
Segno/Segno/Data/Repository/MyPageRepository.swift
Segno/Segno/Domain/UseCase/UserDetailUseCase.swift
Segno/Segno/Entity/UserDetailItem.swift
Segno/Segno/Presentation/ViewController/MyPageViewController.swift
Segno/Segno/Presentation/ViewModel/MyPageViewModel.swift

12/8 #135 
- 기존에 있던 더미데이터들을 삭제하였습니다.
- 서버 스키마에 맞춰서 전반적인 DTO 등을 수정하였습니다.

MyPage 서버와 연결 및 더미데이터 삭제

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Data/Repository/LocationRepository.swift
Segno/Segno/Domain/UseCase/GetAddressUseCase.swift
Segno/Segno/Domain/UseCase/LocationUseCase.swift
Segno/Segno/Presentation/Coordinator/DiaryCoordinator.swift
Segno/Segno/Presentation/View/LocationContentView.swift
Segno/Segno/Presentation/ViewController/DiaryDetailViewController.swift
Segno/Segno/Presentation/ViewController/MapViewController.swift
Segno/Segno/Presentation/ViewModel/DiaryDetailViewModel.swift
Segno/Segno/Presentation/ViewModel/DiaryEditViewModel.swift
Segno/Segno/Presentation/ViewModel/MapViewModel.swift

12/10 #196 #197 #198 #199 #200 #201
- 이제 LocationUseCase는 Location을 바인드하며 위치을 받아오거나 멈추도록 요청하는 역할만 수행합니다.
- 지금은 서버 이슈로 위치를 확인할 수 없습니다.
- 일단 UseCase를 분리했습니다. UseCase를 분리하니 로직이 보다 명료해졌습니다.

전체적인 Location 관련 로직 수정

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Presentation/ViewController/DiaryEditViewController.swift

12/10 #85 
- 어차피 클로저로 액션을 넘겨줘야 하기 때문에 코드 양적인 층면을 봤을 때는 얼마나 효용이 있을지 모르겠습니다.

DiaryEditViewController - imagePicker에 카메라 옵션 추가

---

Segno/Segno/Data/Repository/MusicRepository.swift
Segno/Segno/Data/Session/MusicSession.swift
Segno/Segno/Domain/UseCase/PlayMusicUseCase.swift
Segno/Segno/Entity/DiaryDetail.swift
Segno/Segno/Presentation/View/MusicContentView.swift
Segno/Segno/Presentation/ViewController/DiaryDetailViewController.swift
Segno/Segno/Presentation/ViewModel/DiaryDetailViewModel.swift

12/11 #92 
- 별도의 Observable을 두고 실행됩니다.
- 재생 실패의 경우, 오류에 대한 간단한 설명이 팝업으로 표시됩니다.
- 해당 음원이 다운로드가 완료된 후 바로 재생됩니다.
- 뷰 모델의 이니셜라이즈 시점에 자동재생 설정을 체크하고 자동재생을 수행하면, 음원 데이터의 다운로드가 완료되지 않은 상태에서 재생을 시도하려 하는 것이기 때문에 에러가 발생했습니다.
- 콘솔에 출력되는 로그를 토대로, 애플 서버와의 통신이 직접 일어남을 유추할 수 있었습니다.
- 그래서, 음악 데이터를 가져오는 데 성공했을 때 어떤 처리를 해 주었었는지 주목하고, 해당 부분에 음악 플레이어가 준비가 되었다는 것을 나타내는 프로퍼티를 전달해 주고, 해당 프로퍼티를 옵저빙함으로써 자동재생이 알맞는 타이밍에 되도록 조정했습니다.

음악 세션 Subject 제거 및 자동재생 구현

---

Segno/Segno/Application/AppCoordinator.swift
Segno/Segno/Presentation/Coordinator/LoginCoordinator.swift
Segno/Segno/Presentation/Coordinator/MyPageCoordinator.swift
Segno/Segno/Presentation/Coordinator/TabBar/TabBarCoordinator.swift
Segno/Segno/Presentation/ViewController/LoginViewController.swift
Segno/Segno/Presentation/ViewController/MyPageViewController.swift

12/11
- 특별히 로그아웃 후 재로그인하면 기존 코드상 pushViewContoller()에서 animated가 true로 발동하여 지저분하였습니다.
- 따라서 몇몇 부분에서 false로 바꿔주었습니다.
> Assertion failed: Delegate was changed from time it was first set.
- 이에 설정 탭을 세팅할 때 사용한 Observable을 dispose 시키지 않아서 발생했음을 확인하여 수정하였습니다.

로그아웃 후 로그인 화면으로 이동

---

Segno/Segno/Presentation/ViewController/DiaryEditViewController.swift
Segno/Segno/Presentation/ViewModel/DiaryEditViewModel.swift

12/12
- 위치 추적 버튼을 눌러 ViewModel단에서 위치(Location)을 받아오기만 하고 getAddressUseCase(by: Location) 메서드를 실행시키지 않았던 탓이었습니다.
- 이를 위해 ViewModel단에서 유즈케이스에서 위치를 불러오고 멈추는 부분을 getLocation / stopLocation 메서드로 분리했습니다.

위치 관련 이슈 수정

---

Segno/Segno.xcodeproj/project.pbxproj
Segno/Segno/Extension/UIImageView+.swift
Segno/Segno/Presentation/View/DiaryCell.swift
Segno/Segno/Presentation/View/LocationContentView.swift
Segno/Segno/Presentation/View/MusicContentView.swift
Segno/Segno/Presentation/ViewController/DiaryDetailViewController.swift

12/11
- 이 과정에서 통일된 프로세스를 따르도록, 이미지 세팅 메서드를 extension으로 따로 분리했습니다.
- MarqueeLabel을 음악 쪽에 사용했고, 주소 쪽은 길면 자동으로 줄어들게끔 했습니다.
- 이 과정에서 버튼의 시인성을 포인트 컬러를 활용해 강화했습니다.
- 30인 걸로 아는데, 조금 불편하기는 할 것 같습니다.
- 스택 뷰 기반으로 컨텐츠 뷰 UI 요소들을 리팩토링하는 게 나을까요?

UI 관련 편의 기능 수정

---

Segno/Segno/Data/Repository/MusicRepository.swift
Segno/Segno/Data/Session/ShazamSession.swift
Segno/Segno/Domain/UseCase/SearchMusicUseCase.swift
Segno/Segno/Entity/DiaryDetail.swift
Segno/Segno/Extension/UIFont+.swift
Segno/Segno/Extension/UIViewController+.swift
Segno/Segno/Presentation/Coordinator/TabBar/TabBarCoordinator.swift
Segno/Segno/Presentation/View/LocationContentView.swift
Segno/Segno/Presentation/View/MusicContentView.swift
Segno/Segno/Presentation/View/NicknameCell.swift
Segno/Segno/Presentation/View/SettingsActionSheetCell.swift
Segno/Segno/Presentation/View/SettingsSwitchCell.swift
Segno/Segno/Presentation/View/TagView.swift
Segno/Segno/Presentation/ViewController/DiaryCollectionViewController.swift
Segno/Segno/Presentation/ViewController/DiaryDetailViewController.swift
Segno/Segno/Presentation/ViewController/DiaryEditViewController.swift
Segno/Segno/Presentation/ViewController/MapViewController.swift
Segno/Segno/Presentation/ViewController/MyPageViewController.swift
Segno/Segno/Presentation/ViewController/SettingsViewController.swift
Segno/Segno/Presentation/ViewModel/DiaryDetailViewModel.swift
Segno/Segno/Presentation/ViewModel/DiaryEditViewModel.swift

12/12
- 서라운드 계열은 거의 날렸습니다.
- 마이크 사용 권한이 없는 상태에서 검색을 시도할 때, 앱 오류 창은 잘 뜨지만 콘솔에 reentrancy anomaly was detected 오류가 떴습니다.
- 특정 이벤트가 끝나기 전에 다른 이벤트가 시작되는 것이 문제점임을 파악했습니다.
- 오류와 검색 결과를 Result type으로 묶어서 보내주려고 했던 부분에서 문제가 있을 것이라고 파악했습니다. 해당 오류가 두 번 나왔기 때문에..
- 그래서 검색 결과와 오류를 별개의 Observable로 만들어 주고, 각각을 필요한 곳에서 구독해서 오류에 대해서는 팝업 액션을, 검색 결과에 대해서는 미리 빼 둔 프로퍼티에 저장하는 동작을 수행하도록 변경했습니다.
- Hot observable의 성질을 이용해 검색 결과가 나오면 나오는 대로 표시되게 했고, 검색 결과가 표시된다 하더라도 에러가 있다면 또한 팝업으로 알려줄 수 있으므로 안정성이 상승했다고 여겨집니다.

피드백 반영 및 오류 수정

---

Segno/Segno/Presentation/ViewController/DiaryEditViewController.swift
Segno/Segno/Presentation/ViewController/MapViewController.swift

12/12
- 주소 레이블을 밑에 두고 이를 기준으로 맵뷰화면의 높이를 유동적으로 설정합니다.
- 다크모드에 따라 변경되도록 변경했습니다.

사소한 레이아웃 수정
